name: Build & Publish Images

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
    - name: Set environment variable
      run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/playground-api" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Build and push image by digest
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ matrix.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
        provenance: false
        cache-from: type=gha
        cache-to: type=gha

    - name: Export digest
      run: |
        mkdir -p "/tmp/digests/playground-api"
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/playground-api/${digest#sha256:}"

    - name: Upload digests
      uses: actions/upload-artifact@v3
      with:
        name: playground-api-digests
        path: /tmp/digests/playground-api/*
        if-no-files-found: error
        retention-days: 1

  merge:
    name: Merge digests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set environment variable
      run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/playground-api" >> $GITHUB_ENV

    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        name: playground-api-digests
        path: /tmp/digests/playground-api

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create manifest list and push
      working-directory: /tmp/digests/playground-api
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ env.IMAGE_NAME }}@sha256:%s ' *)

    - name: Inspect image
      run: |
        docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
